### ISSUE TITLE
提交一个低级错误的BUG

### ISSUE THREAD

**Issue by xmqhzs** [MiniKimmy/sketchfab_download#11]
只要模型标题名字中带“&”字符就会下载失败。（很可能其他特殊字符也会导致下载失败）

**Comment by MiniKimmy** [comment]
你好，方便贴一下下载链接吗？

**Comment by MiniKimmy** [comment]
> 只要模型标题名字中带“&”字符就会下载失败。（很可能其他特殊字符也会导致下载失败）

我全部字符都加了，更新试试咯。
