### ISSUE TITLE
对于较少用的文字编码的文件名，读取貌似有些问题

### ISSUE THREAD

**Issue by visnz** [MiniKimmy/sketchfab_download#12]
![image](https://user-images.githubusercontent.com/26197210/119231219-45effc00-bb52-11eb-9b72-02826813ba1e.png)

**Comment by MiniKimmy** [comment]
> ![image](https://user-images.githubusercontent.com/26197210/119231219-45effc00-bb52-11eb-9b72-02826813ba1e.png)
> 
> 

确实，特殊语言会有问题，我编码之后再用，不过带来的缺点是保存的文件名就变丑了。
代码已提交。
