### ISSUE TITLE
sf更新了贴图地址造成出错

### ISSUE THREAD

**Issue by x1911** [MiniKimmy/sketchfab_download#6]
sf好像在原本的 '/i/models/' + modelId + '/textures?optimized=1
中又多加了一个id，现在的贴图地址类似这样
https://media.sketchfab.com/models/088b892ce32a464c8b305c6c893cae56/de8362794b7c4d95b59f9055c3fb5f6d/textures/ceecd77ab44b465ebbe83d19e73940d4/81bd427682ff44a68d1577371935f952.jpeg

texturesData = data['/i/models/' + modelId + '/textures?optimized=1']['results'] 好像是这里没能获取到图片地址，报错

造成了下载出错，能看看是哪里的问题吗？
万分感谢

**Comment by MiniKimmy** [comment]
确实，我昨天也发现了，爬的数据里的贴图下载链接找不到了。也就是说贴图下载不了QAQ。

如果把下载贴图的相关代码行注释掉就运行正常了。sketchfab的网页可能更新了，目前还没找到怎么下载模型对应的贴图

**Comment by x1911** [comment]
信息仍然是在 
```
<div class="dom-data-container" style="display:none;" id="js-dom-data-prefetched-data">
```
 这个div下，去掉div注释 <!--，替换 &#34; 为引号，再parse 就可以得到完整的对象
在 metadata 的子元素中 filepath，有相关的图片 textures/base_AO.jpeg，
但缺乏对应的服务器地址，看情况好像要自己拼出来

**Comment by MiniKimmy** [comment]
> 信息仍然是在
> 
> ```
> <div class="dom-data-container" style="display:none;" id="js-dom-data-prefetched-data">
> ```
> 
> 这个div下，去掉div注释 <!--，替换 " 为引号，再parse 就可以得到完整的对象
> 在 metadata 的子元素中 filepath，有相关的图片 textures/base_AO.jpeg，
> 但缺乏对应的服务器地址，看情况好像要自己拼出来

代码已更改，可以下载啦。

**Comment by x1911** [comment]
非常感谢🙏

尝试了一下，无法启动 blender 转换，下载的文件也被删掉了

![image](https://user-images.githubusercontent.com/8219031/116837452-173ecf80-abfd-11eb-858c-bfb0cc4e11dd.png)

是目录的原因不？

**Comment by MiniKimmy** [comment]
> 非常感谢🙏
> 
> 
> 
> 尝试了一下，无法启动 blender 转换，下载的文件也被删掉了
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/8219031/116837452-173ecf80-abfd-11eb-858c-bfb0cc4e11dd.png)
> 
> 
> 
> 是目录的原因不？

download那个是正常了，你这个是到了第二步 blender部分，这个问题和之前的[issue#1](https://github.com/MiniKimmy/sketchfab_download/issues/1)一样，是缺少了一些依赖导致，

**Comment by ifishzz** [comment]
> 确实，我昨天也发现了，爬的数据里的贴图下载链接发现了。而是贴图下载不了QAQ。
> 
> 如果把下载贴图的相关代码行注释掉就运行正常了。sketchfab的网页可能更新了，目前还没找到怎么下载模型对应的贴图

将下载链接改为 url/embed 即可正常下载

**Comment by MiniKimmy** [comment]
> > 确实，我昨天也发现了，爬的数据里的贴图下载链接发现了。而是贴图下载不了QAQ。
> 
> > 
> 
> > 如果把下载贴图的相关代码行注释掉就运行正常了。sketchfab的网页可能更新了，目前还没找到怎么下载模型对应的贴图
> 
> 
> 
> 将下载链接改为 url/embed 即可正常下载

是的，昨天已经默认补上啦，保持原来的url输入就好。 他下载这步ok了，是到blender没通
